# Publish modules under cBioPortal/cbioportal-frontend/packages directory to npm registry
name: cBioPortal Frontend Module Publish

on:
  repository_dispatch:
    types: [cbioportal-frontend-package-update]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.LERNA_PUBLISH_BOT_GITHUB_TOKEN }}
          repository: cBioPortal/cbioportal-frontend
      # lerna needs tags to be able to determine what's changed
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v1
        with:
          node-version: '16.13.1'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn policies set-version 1.22.15
      - run: yarn --frozen-lockfile
      - run: yarn updatePackageVersion
      - run: yarn buildModules
      - run: yarn publishModules
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
